### PR TITLE
Add example configuration

### PR DESCRIPTION
**Pull request by luator**
## Description
Add a `example` directory that contains a demo config file which can be used to run the code in simulation.

This is what I am currently using for testing.  I think it is good for newcomers to have an example setup that can just be run without further background knowledge I propose to add it to the repository.

While with this configuration I can run the code without error, the robot doesn't move a lot, so I am actually not sure if the specific configuration makes sense.  Please let me know if I should change something.

## How I Tested

By running it as described in the README.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by simonguist** [comment]
Looks good.
Small correction, in `hysr_demos.json`, `robot_integrity_check` should probably be set to `false`.
Maybe also mention in the readme that for learning the parameters from `hysr_one_ball_default_sim.json` should be used (we should update them as well with the new fields)

**Review by vincentberenz — APPROVED** [review]

**Comment by luator** [comment]
@simonguist 
I actually have some trouble with running the learning (i.e. `hysr_one_ball_ppo`).

- With the current settings it fails because in `openai_ppo_default.json`
  `"load_path": "/tmp/model"` is set but that file doesn't exist for me.  I
  could fix this by setting `"load_path": null` in that file.  Should I push
  this change on the existing file or rather add a separate config file for the
  example?

- With the above change I can run `hysr_one_ball_ppo` using `hysr_demos.json`.
  The robot in the simulation starts moving and there is some continuous output
  in the terminal.  However, when I switch to `hysr_one_ball_default_sim.json`
  (and add the new keys there as well as `"real_robot":false` like in
  `hysr_demos.json`), it hangs in the beginning after printing the following
  lines:

      -------STD-------
      Tensor("ppo2_model/Exp:0", shape=(1, 8), dtype=float32)

  Is this expected?

**Comment by simonguist** [comment]
Yes, you are right: `"load_path": null` should be the default. You can push it like this.

As for the hanging, I'm not sure what's causing it. This needs to be investigated.

**Review by simonguist — APPROVED** [review]

**Comment by luator** [comment]
> As for the hanging, I'm not sure what's causing it. This needs to be investigated.

To not delay this PR too much, let's fix that problem in a separate one, once we found the reason.

**Pull request merged**
